spring:
  datasource:
    url: jdbc:mysql://192.168.0.170:3306/store
    username: softcube
    password: Brasil@77!
  jpa:
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/migration/changelog.xml